version: '3.8'

services:
  postgres:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: testing
      POSTGRES_PASSWORD: testing
      POSTGRES_DB: grup3_db
    ports:
      - "5432:5432"
    restart: always

  adminer: 
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres